In [59]:
# Consider the room to be of dimension 10m * 10m * 3m and resolution is taken to be 0.01 m.
Ambient_Temp = 35 # in degree celsius.
Delta_T_Max = 200 # in degree celsius.
Saturation_time = 300 # in seconds.
Attenuation_coeff = 0.2 # in m^-1
source_pos_x = 0
source_pos_y = 0
source_pos_z = 0
L_T = 2 # in meters.
simulation_time = 1500 # in seconds.

In [65]:
import numpy as np
X_Coordinate_time = np.array(np.arange(-5, 5.1, 0.1))
X_Coordinate_time = np.tile(X_Coordinate_time, (101, 1))
X_Coordinate_time = np.tile(X_Coordinate_time, (31, 1, 1))
X_Coordinate_time = np.tile(X_Coordinate_time, (101, 1, 1, 1))

Y_Coordinate_time = np.array(np.arange(-5, 5.1, 0.1)).reshape(101, 1)
Y_Coordinate_time = np.tile(Y_Coordinate_time, (1, 101))
Y_Coordinate_time = np.tile(Y_Coordinate_time, (31, 1, 1))
Y_Coordinate_time = np.tile(Y_Coordinate_time, (101, 1, 1, 1))

Z_Coordinate_time = np.zeros((101, 101))
Z_Coordinate_time = np.tile(Z_Coordinate_time, (31, 1, 1))
for i in range(0,31):
    Z_Coordinate_time[i, :, :] = i/10
Z_Coordinate_time = np.tile(Z_Coordinate_time, (101, 1, 1, 1))

Time_array = np.zeros((31, 101, 101))
Time_array = np.tile(Time_array, (101, 1, 1, 1))
for i in range(0,101):
    Time_array[i, :, :, :] = i + 250

H_Hold = Delta_T_Max * (np.log(1 + (Time_array))/np.log(1 + Saturation_time)) * np.exp((-1) * Attenuation_coeff * np.sqrt(((X_Coordinate_time ** 2) + (Y_Coordinate_time ** 2))))
V_Hold = 5.386 * (((Z_Coordinate_time / L_T) + 0.558) ** 3.205) * np.exp((-4.057) * (Z_Coordinate_time / L_T))
array_temp_dist = Ambient_Temp + (H_Hold * V_Hold) 
# Source Temperature is found at array_temp_dist(501, 501, 151)

In [66]:
array_temp_dist[:, 16, 51, 51]

array([ 97.08088779,  97.15403315,  97.2268988 ,  97.29948685,
        97.37179944,  97.44383863,  97.51560648,  97.58710503,
        97.65833631,  97.72930228,  97.80000493,  97.87044621,
        97.94062803,  98.0105523 ,  98.0802209 ,  98.14963571,
        98.21879855,  98.28771126,  98.35637563,  98.42479345,
        98.49296649,  98.56089648,  98.62858516,  98.69603423,
        98.76324538,  98.83022029,  98.89696062,  98.96346799,
        99.02974403,  99.09579034,  99.16160852,  99.22720012,
        99.29256671,  99.35770983,  99.42263099,  99.48733171,
        99.55181347,  99.61607776,  99.68012603,  99.74395973,
        99.8075803 ,  99.87098915,  99.93418769,  99.99717731,
       100.05995939, 100.12253528, 100.18490634, 100.24707391,
       100.30903931, 100.37080385, 100.43236882, 100.49373551,
       100.55490521, 100.61587915, 100.67665861, 100.7372448 ,
       100.79763897, 100.85784231, 100.91785604, 100.97768134,
       101.03731939, 101.09677137, 101.15603842, 101.21

In [58]:
np.array([1,3,4,5]) + 2

array([3, 5, 6, 7])

In [62]:
np.exp(0)

np.float64(1.0)

In [15]:
1 ** 4.5

1.0

In [45]:
A = np.array(np.arange(-5, 5.01, 0.01));

In [46]:
A_stack = np.tile(A, (10, 1))

In [47]:
A_stack

array([[-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
       [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
       [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
       [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
       [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ]], shape=(10, 1001))

In [49]:
A_stack2 = np.tile(A_stack, (10, 1, 1))
A_stack2

array([[[-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        ...,
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ]],

       [[-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        ...,
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ]],

       [[-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        ...,
        [-5.  , -4.99, -4.98, ...,  4.98,  4.99,  5.  ],
        [-5.  , -4.99, -4.98, ...,  4.98,  4.